--- 
- name: creating consul config dir
  ansible.builtin.file: 
    path: /etc/consul.d
    state: directory 
    mode: '0755'
  when: cluster_mode == "client"

- name: moving consul.hcl
  template: 
    src: ../templates/consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: root
    group: root
    mode: '0755'
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['nomad_client'] }}"
  loop_control:
    index_var: count

- name: create ACL dir
  ansible.builtin.file: 
    path: /ops/shared/config
    state: directory
    mode: '0755'
  when: cluster_mode == "client"