---
- name: install consul 
  import_tasks: consul_install.yml
  when: cluster_mode == "client"

- name: configure consul
  import_tasks: consul_config.yml 

- name: run consul 
  import_tasks: consul_run.yml