---
# destroy linodes

- name: destroying linodes
  hosts: localhost
  connection: local
  vars_files:
      - group_vars/nomad/vars
      - group_vars/nomad/secret_vars
  
  vars:
    count: '{{ cluster_size - 1 }}'

  tasks:
  - name: deleting linodes except provisioner
    linode.cloud.instance:
      label: '{{ instance_prefix }}-client-{{ item | int + 1 }}-{{ uuid }}'
      api_token: '{{ api_token }}'
      state: absent
    with_sequence: count='{{ count }}'